### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [zacanger/is-program-installed#5]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by zacanger** [comment]
Hi @JamieSlome, not sure how I never saw this but my email address is zac at my username dot com (and should also be listed publicly on my profile for anyone logged in to GH). I'll look into adding `SECURITY.md` files in all my active projects :)

**Comment by JamieSlome** [comment]
Hi @zacanger - no worries and thank you for your response :)

We sent a couple of e-mails out a while ago but didn't get a response. If it is easier, you can find the report directly here:
https://huntr.dev/bounties/79cf0270-32ec-4403-bf1d-c032f5894e6f/

It is private and only accessible to you 👍
